package com.martinlinha.c3faces.util;

import com.martinlinha.c3faces.script.Property;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Class wraps StringBuilder and contains methods to append .js specific strings.
 *
 * @author Martin Linha
 */
public class JSBuilder {

    private StringBuilder builder = new StringBuilder();

    public JSBuilder() {
    }

    /**
     * Creates new instance of this class
     *
     * @return New JSBuiler instance
     */
    public static JSBuilder build() {
        return new JSBuilder();
    }

    /**
     * Appends "c3" string to wrapped StringBuilder
     *
     * @return Reference to same class instance
     */
    public JSBuilder c3() {
        builder.append("c3");
        return this;
    }

    /**
     * Appends .js var with specified name to wrapped StringBuilder
     *
     * @param var Name of var
     * @return Reference to same class instance
     */
    public JSBuilder var(String var) {
        builder.append("var ").append(var).append(" = ");
        return this;
    }

    /**
     * Appends ";" string and break line to wrapped StringBuilder and
     *
     * @return Reference to same class instance
     */
    public JSBuilder endLine() {
        builder.append("; \n");
        return this;
    }

    /**
     * Returns result of wrapped StringBuilder
     *
     * @return Result of wrapped StringBuilder
     */
    public String getResult() {
        String res = builder.toString();
        builder = new StringBuilder();
        return res;
    }

    /**
     * Appends "data" in which inserts all scripts generated by specified collection of properties to wrapped StringBuilder
     *
     * @param properties Properties which generated script should be appended
     * @return Reference to same class instance
     */
    public JSBuilder generate(Collection<Property> properties) {
        builder.append(".generate({");
        List<Property> attributes = new ArrayList<>(properties);
        for (int i = 0; i < attributes.size(); i++) {
            Property attr = attributes.get(i);
            String script = attr.getScript();
            if (i > 0 && !script.isEmpty()) {
                builder.append(", ");
            }
            builder.append(script);
        }

        builder.append("})");
        return this;
    }
}
